services:
  rabbit:
    container_name: cv-rabbit
    image: rabbitmq
    ports:
      - "5672:5672"

  api:
    container_name: cv-api
    build:
      context: ./apps/api
    ports:
      - "4000:4000"

  auth:
    container_name: cv-auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://auth_user:auth_password@db:5432/auth_db"
    env_file: ./apps/auth/.env

  fit-ai:
    container_name: cv-fit-ai
    build:
      context: .
      dockerfile: ./apps/fit-ai/Dockerfile

  db:
    container_name: cv-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
